### ISSUE TITLE
Consider adding Rocket Fuel to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [stec-ug-haftungsbeschrankt/rocket-fuel#1]
Hey @schickst, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by schickst** [comment]
Thanks for the interest. Initially I only added it for a prototype, but then went back to Diesel. SeaOrm looks promising but I do not have the feeling that I should already use it in production, yet. Because of it I removed the dependency again.
This might change in the future again, when SeaOrm is more mature.
